FROM openjdk:17-jdk-slim

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN apt-get update && apt-get install -y maven && \
    mvn clean package -DskipTests && \
    cp target/*.jar app.jar

EXPOSE 8085

CMD ["java", "-jar", "app.jar"]
