-- Schema SQL para MySQL (Empuje Comunitario)
DROP DATABASE IF EXISTS empuje;
CREATE DATABASE empuje CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE empuje;

-- Usuarios
CREATE TABLE usuarios (
  id CHAR(36) NOT NULL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  nombre VARCHAR(100),
  apellido VARCHAR(100),
  telefono VARCHAR(50),
  email VARCHAR(200) NOT NULL UNIQUE,
  rol VARCHAR(50) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  activo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Inventario
CREATE TABLE inventario (
  id CHAR(36) NOT NULL PRIMARY KEY,
  categoria VARCHAR(50) NOT NULL,
  descripcion TEXT,
  cantidad INT NOT NULL DEFAULT 0,
  activo BOOLEAN DEFAULT TRUE,
  auditoria JSON DEFAULT (JSON_ARRAY()),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Eventos
CREATE TABLE eventos (
  id CHAR(36) NOT NULL PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL,
  descripcion TEXT,
  fecha DATETIME NOT NULL,
  participantes JSON DEFAULT (JSON_ARRAY()),
  donaciones_usadas JSON DEFAULT (JSON_ARRAY()),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Auditoría
CREATE TABLE auditoria (
  id CHAR(36) NOT NULL PRIMARY KEY,
  entidad VARCHAR(100),
  entidad_id CHAR(36),
  operacion VARCHAR(50),
  usuario_id CHAR(36),
  detalle JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
