version: '3.8'

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/empuje_comunitario?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - empuje-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: empuje_comunitario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - empuje-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysql
    networks:
      - empuje-network

networks:
  empuje-network:
    driver: bridge

volumes:
  mysql_data:
